import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax19widget/generated/GeneratedMenubarWidget3.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax19widget/generated/GeneratedUploadImageWidget4.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax19widget/generated/GeneratedForeveryDonationgetaTreeSaplingWidget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax19widget/generated/GeneratedDonateWidget2.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax19widget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax19widget/generated/GeneratedDonateRedeemWidget.dart';

/* Frame iPhone 14 Pro Max - 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax19Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 158.0,
                              right: null,
                              bottom: null,
                              width: 132.0,
                              height: 53.0,
                              child: GeneratedDonateWidget2(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 236.0,
                              right: null,
                              bottom: null,
                              width: 385.0,
                              height: 81.0,
                              child: GeneratedGroup22Widget(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 852.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 61.0,
                              child: GeneratedMenubarWidget3(),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 326.0,
                              height: 78.0,
                              child:
                                  GeneratedForeveryDonationgetaTreeSaplingWidget(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 764.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 60.0,
                              child: GeneratedUploadImageWidget4(),
                            ),
                            Positioned(
                              left: 80.0,
                              top: 775.0,
                              right: null,
                              bottom: null,
                              width: 261.0,
                              height: 40.0,
                              child: GeneratedDonateRedeemWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
