import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedintropagewidget/generated/GeneratedWelcometotheMostImaginativeMarketplaceRevolutionizeyour.dart';
import 'package:flutterapp/femmefindsapp/generatedintropagewidget/generated/GeneratedShoppingBagWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedintropagewidget/generated/GeneratedButtonsWidget.dart';

/* Frame IntroPage
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntroPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1004.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 238.0,
                              right: null,
                              bottom: null,
                              width: 363.0,
                              height: 766.0,
                              child:
                                  GeneratedWelcometotheMostImaginativeMarketplaceRevolutionizeyour(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 714.0,
                              right: null,
                              bottom: null,
                              width: 337.0,
                              height: 136.0,
                              child: GeneratedButtonsWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 198.0,
                              right: null,
                              bottom: null,
                              width: 290.0,
                              height: 236.0,
                              child: GeneratedShoppingBagWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
