import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedsigninwidget1/generated/GeneratedLetssignyouinWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatedsigninwidget1/generated/GeneratedLoginButtonWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatedsigninwidget1/generated/GeneratedCreateanAccountSignupWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatedsigninwidget1/generated/GeneratedForgotpasswordWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatedsigninwidget1/generated/GeneratedGoogleFacebookSigninWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatedsigninwidget1/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatedsigninwidget1/generated/GeneratedUsernameWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatedsigninwidget1/generated/GeneratedLogoWidget1.dart';

/* Frame Sign-in
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 226.0,
                              top: 580.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 23.0,
                              child: GeneratedForgotpasswordWidget1(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 484.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 81.0,
                              child: GeneratedPasswordWidget1(),
                            ),
                            Positioned(
                              left: 77.0,
                              top: 288.0,
                              right: null,
                              bottom: null,
                              width: 261.0,
                              height: 45.0,
                              child: GeneratedLetssignyouinWidget1(),
                            ),
                            Positioned(
                              left: 178.0,
                              top: 202.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 71.0,
                              child: GeneratedLogoWidget1(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 357.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 90.0,
                              child: GeneratedUsernameWidget1(),
                            ),
                            Positioned(
                              left: 105.0,
                              top: 692.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 123.0,
                              child: GeneratedGoogleFacebookSigninWidget1(),
                            ),
                            Positioned(
                              left: 64.0,
                              top: 844.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 38.0,
                              child: GeneratedCreateanAccountSignupWidget1(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 616.0,
                              right: null,
                              bottom: null,
                              width: 230.0,
                              height: 56.0,
                              child: GeneratedLoginButtonWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
