import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax17widget/generated/GeneratedReviewbyourteamdependingonproductqualityWidget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax17widget/generated/GeneratedLine19Widget1.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax17widget/generated/GeneratedThankyouForsellingYourProductWidget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax17widget/generated/GeneratedEllipse15Widget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax17widget/generated/GeneratedGroup16Widget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax17widget/generated/GeneratedTransactionthroughyourwalletWidget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax17widget/generated/GeneratedEllipse18Widget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax17widget/generated/GeneratedMenubarWidget5.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax17widget/generated/GeneratedLeftarrow4Widget.dart';

/* Frame iPhone 14 Pro Max - 17
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax17Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 170.0,
                              right: null,
                              bottom: null,
                              width: 399.0,
                              height: 98.0,
                              child:
                                  GeneratedThankyouForsellingYourProductWidget(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 389.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 34.0,
                              child: GeneratedEllipse15Widget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 371.0,
                              right: null,
                              bottom: null,
                              width: 355.0,
                              height: 152.0,
                              child:
                                  GeneratedReviewbyourteamdependingonproductqualityWidget(),
                            ),
                            Positioned(
                              left: 12.0,
                              top: 606.0,
                              right: null,
                              bottom: null,
                              width: 28.0,
                              height: 34.0,
                              child: GeneratedEllipse18Widget(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 580.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 88.0,
                              child:
                                  GeneratedTransactionthroughyourwalletWidget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 423.0,
                              right: null,
                              bottom: null,
                              width: 175.0,
                              height: 0.0,
                              child: GeneratedLine19Widget1(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 849.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 61.0,
                              child: GeneratedMenubarWidget5(),
                            ),
                            Positioned(
                              left: 58.87646484375,
                              top: 745.0,
                              right: null,
                              bottom: null,
                              width: 257.5187683105469,
                              height: 48.0,
                              child: GeneratedGroup16Widget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 36.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedLeftarrow4Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
