import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedsellproductswidget/generated/GeneratedSellYourProductsWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedsellproductswidget/generated/GeneratedProductsWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedsellproductswidget/generated/GeneratedMenu1Widget1.dart';
import 'package:flutterapp/femmefindsapp/generatedsellproductswidget/generated/GeneratedMenubarWidget.dart';

/* Frame SellProducts
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSellProductsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 30.0,
                              child: GeneratedMenu1Widget1(),
                            ),
                            Positioned(
                              left: 36.0,
                              top: 92.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 40.0,
                              child: GeneratedSellYourProductsWidget(),
                            ),
                            Positioned(
                              left: 70.0,
                              top: 218.0,
                              right: null,
                              bottom: null,
                              width: 291.0,
                              height: 597.0,
                              child: GeneratedProductsWidget(),
                            ),
                            Positioned(
                              left: 45.0,
                              top: 863.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 61.0,
                              child: GeneratedMenubarWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
