import 'package:flutter/material.dart';

/* Rectangle image 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage1Widget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 63.0,
      height: 86.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/763c6f0283b0159acdd2972a1ab87c78906442c9.png",
          color: null,
          fit: BoxFit.cover,
          width: 63.0,
          height: 86.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
