import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedgroup20widget/generated/GeneratedAshokaWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedgroup20widget/generated/GeneratedCardiaWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedgroup20widget/generated/GeneratedMangoWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedgroup20widget/generated/GeneratedGroup18Widget1.dart';
import 'package:flutterapp/femmefindsapp/generatedgroup20widget/generated/GeneratedGroup19Widget1.dart';

/* Group Group 20
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup20Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 338.0,
      height: 222.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(0.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 338.0,
              height: 78.0,
              child: GeneratedGroup18Widget1(),
            ),
            Positioned(
              left: 10.0,
              top: 78.0,
              right: null,
              bottom: null,
              width: 321.0,
              height: 144.0,
              child: GeneratedGroup19Widget1(),
            ),
            Positioned(
              left: 37.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 67.0,
              height: 29.0,
              child: GeneratedMangoWidget(),
            ),
            Positioned(
              left: 35.0,
              top: 132.0,
              right: null,
              bottom: null,
              width: 65.0,
              height: 29.0,
              child: GeneratedCardiaWidget(),
            ),
            Positioned(
              left: 36.0,
              top: 177.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 29.0,
              child: GeneratedAshokaWidget(),
            )
          ]),
    ));
  }
}
