import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedorderplacedwidget/generated/GeneratedOrderPlacedSuccessfullyWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedorderplacedwidget/generated/GeneratedContinueShoppingWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedorderplacedwidget/generated/GeneratedAccept1Widget.dart';

/* Frame OrderPlaced
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrderPlacedWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 803.0,
                              right: null,
                              bottom: null,
                              width: 345.0,
                              height: 64.0,
                              child: GeneratedContinueShoppingWidget(),
                            ),
                            Positioned(
                              left: 25.0,
                              top: 311.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 40.0,
                              child: GeneratedOrderPlacedSuccessfullyWidget(),
                            ),
                            Positioned(
                              left: 75.0,
                              top: 436.0,
                              right: null,
                              bottom: null,
                              width: 280.0,
                              height: 280.0,
                              child: GeneratedAccept1Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
