import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax18widget/generated/GeneratedRemoveWidget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax18widget/generated/GeneratedUploadImageWidget5.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax18widget/generated/GeneratedQtyWidget2.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax18widget/generated/GeneratedUploadImageWidget6.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax18widget/generated/GeneratedProductInfoWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax18widget/generated/GeneratedMenubarWidget4.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax18widget/generated/GeneratedPriceWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax18widget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax18widget/generated/GeneratedShoppingcart1Widget2.dart';

/* Frame iPhone 14 Pro Max - 18
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax18Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 346.0,
                              top: 31.0,
                              right: null,
                              bottom: null,
                              width: 31.0,
                              height: 31.0,
                              child: GeneratedShoppingcart1Widget2(),
                            ),
                            Positioned(
                              left: 23.0,
                              top: 318.0,
                              right: null,
                              bottom: null,
                              width: 82.0,
                              height: 33.0,
                              child: GeneratedQtyWidget2(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 409.0,
                              height: 77.0,
                              child: GeneratedProductInfoWidget1(),
                            ),
                            Positioned(
                              left: 117.0,
                              top: 320.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 30.99993896484375,
                              child: GeneratedPriceWidget1(),
                            ),
                            Positioned(
                              left: 233.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 184.0,
                              height: 49.0,
                              child: GeneratedUploadImageWidget5(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 168.0,
                              height: 49.0,
                              child: GeneratedUploadImageWidget6(),
                            ),
                            Positioned(
                              left: 41.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 43.0,
                              child: GeneratedRemoveWidget(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 516.0,
                              right: null,
                              bottom: null,
                              width: 430.0,
                              height: 205.0,
                              child: GeneratedGroup23Widget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 61.0,
                              child: GeneratedMenubarWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
