import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax20widget/generated/GeneratedRectangle192Widget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax20widget/generated/GeneratedThankyouforrecyclingyourproductWidget.dart';
import 'package:flutterapp/femmefindsapp/generatediphone14promax20widget/generated/GeneratedMenubarWidget6.dart';

/* Frame iPhone 14 Pro Max - 20
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone14ProMax20Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 434.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 434.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 14.0,
                              top: 278.0,
                              right: null,
                              bottom: null,
                              width: 436.0,
                              height: 98.0,
                              child:
                                  GeneratedThankyouforrecyclingyourproductWidget(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 849.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 61.0,
                              child: GeneratedMenubarWidget6(),
                            ),
                            Positioned(
                              left: 51.0,
                              top: 466.0,
                              right: null,
                              bottom: null,
                              width: 352.0,
                              height: 258.0,
                              child: GeneratedRectangle192Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
