import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedproductimagecapturewidget/generated/GeneratedLeftarrow3Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedproductimagecapturewidget/generated/GeneratedUploadImageWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedproductimagecapturewidget/generated/GeneratedContentWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedproductimagecapturewidget/generated/GeneratedSellButtonWidget1.dart';

/* Frame ProductImageCapture
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProductImageCaptureWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 53.0,
                              top: 229.0,
                              right: null,
                              bottom: null,
                              width: 325.0,
                              height: 429.0,
                              child: GeneratedContentWidget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 36.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedLeftarrow3Widget(),
                            ),
                            Positioned(
                              left: 81.0,
                              top: 742.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 60.0,
                              child: GeneratedUploadImageWidget(),
                            ),
                            Positioned(
                              left: 92.0,
                              top: 830.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 63.0,
                              child: GeneratedSellButtonWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
