import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedClothesWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedHairCareWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedPeronalCareWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedSellProductsWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedMakeupWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedSkinCareWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedExplorebarWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedMenubarWidget1.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedSellExpiredProductsWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedexplorewidget/generated/GeneratedMakeuptoolWidget.dart';

/* Frame Explore
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExploreWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1102.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 415.0,
                            height: 1102.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(30.0),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(30.0),
                                    child: Image.asset(
                                      "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                      color: null,
                                      fit: BoxFit.cover,
                                      width: 415.0,
                                      height: 1102.0,
                                      colorBlendMode: BlendMode.dstATop,
                                    ),
                                  ),
                                  Positioned(
                                    left: 37.0,
                                    top: 26.0,
                                    right: null,
                                    bottom: null,
                                    width: 348.0,
                                    height: 45.0,
                                    child: GeneratedExplorebarWidget(),
                                  ),
                                  Positioned(
                                    left: 64.0,
                                    top: 136.0,
                                    right: null,
                                    bottom: null,
                                    width: 287.0,
                                    height: 81.0,
                                    child: GeneratedClothesWidget(),
                                  ),
                                  Positioned(
                                    left: 64.0,
                                    top: 376.0,
                                    right: null,
                                    bottom: null,
                                    width: 287.0,
                                    height: 81.0,
                                    child: GeneratedMakeuptoolWidget(),
                                  ),
                                  Positioned(
                                    left: 64.0,
                                    top: 256.0,
                                    right: null,
                                    bottom: null,
                                    width: 287.0,
                                    height: 81.0,
                                    child: GeneratedMakeupWidget(),
                                  ),
                                  Positioned(
                                    left: 64.0,
                                    top: 496.0,
                                    right: null,
                                    bottom: null,
                                    width: 287.0,
                                    height: 81.0,
                                    child: GeneratedSkinCareWidget(),
                                  ),
                                  Positioned(
                                    left: 64.0,
                                    top: 976.0,
                                    right: null,
                                    bottom: null,
                                    width: 287.0,
                                    height: 81.0,
                                    child: GeneratedHairCareWidget(),
                                  ),
                                  Positioned(
                                    left: 64.0,
                                    top: 616.0,
                                    right: null,
                                    bottom: null,
                                    width: 287.0,
                                    height: 81.0,
                                    child: GeneratedPeronalCareWidget(),
                                  ),
                                  Positioned(
                                    left: 64.0,
                                    top: 856.0,
                                    right: null,
                                    bottom: null,
                                    width: 287.0,
                                    height: 81.0,
                                    child: GeneratedSellExpiredProductsWidget(),
                                  ),
                                  Positioned(
                                    left: 64.0,
                                    top: 736.0,
                                    right: null,
                                    bottom: null,
                                    width: 287.0,
                                    height: 81.0,
                                    child: GeneratedSellProductsWidget1(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 41.0,
              top: 856.0,
              right: null,
              bottom: null,
              width: 333.0,
              height: 61.0,
              child: GeneratedMenubarWidget1(),
            )
          ]),
    ));
  }
}
