import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedclothstorewidget/generated/GeneratedCloth5Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedclothstorewidget/generated/GeneratedRectangle160Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedclothstorewidget/generated/GeneratedCloth4Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedclothstorewidget/generated/GeneratedCloth2Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedclothstorewidget/generated/GeneratedCloth6Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedclothstorewidget/generated/GeneratedMenu1Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedclothstorewidget/generated/GeneratedCloth1Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedclothstorewidget/generated/GeneratedCloth3Widget.dart';

/* Frame ClothStore
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedClothStoreWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 648.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 226.0,
                              child: GeneratedCloth6Widget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 345.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 226.0,
                              child: GeneratedCloth5Widget(),
                            ),
                            Positioned(
                              left: 249.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 226.0,
                              child: GeneratedCloth4Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 60.0,
                              right: null,
                              bottom: null,
                              width: 27.0,
                              height: 30.0,
                              child: GeneratedMenu1Widget(),
                            ),
                            Positioned(
                              left: 71.0,
                              top: 53.0,
                              right: null,
                              bottom: null,
                              width: 107.0,
                              height: 48.0,
                              child: GeneratedCloth3Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 403.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 226.0,
                              child: GeneratedCloth2Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 127.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 226.0,
                              child: GeneratedCloth1Widget(),
                            ),
                            Positioned(
                              left: 20.0,
                              top: 679.0,
                              right: null,
                              bottom: null,
                              width: 163.0,
                              height: 226.0,
                              child: GeneratedRectangle160Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
