import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generateddetailofsellprodwidget/generated/GeneratedSellYourProductsWidget1.dart';
import 'package:flutterapp/femmefindsapp/generateddetailofsellprodwidget/generated/GeneratedItemsWidget.dart';
import 'package:flutterapp/femmefindsapp/generateddetailofsellprodwidget/generated/GeneratedLeftarrow1Widget.dart';
import 'package:flutterapp/femmefindsapp/generateddetailofsellprodwidget/generated/GeneratedPendingWidget.dart';
import 'package:flutterapp/femmefindsapp/generateddetailofsellprodwidget/generated/Generated1Widget1.dart';
import 'package:flutterapp/femmefindsapp/generateddetailofsellprodwidget/generated/GeneratedSellButtonWidget.dart';
import 'package:flutterapp/femmefindsapp/generateddetailofsellprodwidget/generated/GeneratedSoldWidget.dart';

/* Frame DetailofSellProd
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDetailofSellProdWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1527.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 1527.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 1527.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 40.0,
                              child: GeneratedSellYourProductsWidget1(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 36.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedLeftarrow1Widget(),
                            ),
                            Positioned(
                              left: 68.0,
                              top: 925.0,
                              right: null,
                              bottom: null,
                              width: 294.0,
                              height: 266.0,
                              child: GeneratedPendingWidget(),
                            ),
                            Positioned(
                              left: 68.0,
                              top: 1219.0,
                              right: null,
                              bottom: null,
                              width: 294.0,
                              height: 266.0,
                              child: GeneratedSoldWidget(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 174.0,
                              right: null,
                              bottom: null,
                              width: 301.0,
                              height: 618.0,
                              child: GeneratedItemsWidget(),
                            ),
                            Positioned(
                              left: 69.0,
                              top: 820.0,
                              right: null,
                              bottom: null,
                              width: 293.0,
                              height: 77.0,
                              child: GeneratedSellButtonWidget(),
                            ),
                            Positioned(
                              left: 261.0,
                              top: 208.0,
                              right: null,
                              bottom: null,
                              width: 22.0,
                              height: 62.0,
                              child: Generated1Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
