import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedsellexpireprodwidget/generated/GeneratedDownarrow1Widget1.dart';
import 'package:flutterapp/femmefindsapp/generatedsellexpireprodwidget/generated/GeneratedGroup18Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedsellexpireprodwidget/generated/GeneratedExpiryDateWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedsellexpireprodwidget/generated/GeneratedMenubarWidget2.dart';
import 'package:flutterapp/femmefindsapp/generatedsellexpireprodwidget/generated/GeneratedLeftarrow2Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedsellexpireprodwidget/generated/GeneratedGroup19Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedsellexpireprodwidget/generated/GeneratedSellButtonWidget2.dart';
import 'package:flutterapp/femmefindsapp/generatedsellexpireprodwidget/generated/GeneratedUploadImageWidget2.dart';
import 'package:flutterapp/femmefindsapp/generatedsellexpireprodwidget/generated/GeneratedRectangle2Widget7.dart';

/* Frame SellExpireProd
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSellExpireProdWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 650.0,
                              right: null,
                              bottom: null,
                              width: 250.0,
                              height: 60.0,
                              child: GeneratedUploadImageWidget2(),
                            ),
                            Positioned(
                              left: 92.0,
                              top: 750.0,
                              right: null,
                              bottom: null,
                              width: 246.0,
                              height: 63.0,
                              child: GeneratedSellButtonWidget2(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 36.0,
                              right: null,
                              bottom: null,
                              width: 30.0,
                              height: 30.0,
                              child: GeneratedLeftarrow2Widget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 178.0,
                              right: null,
                              bottom: null,
                              width: 338.0,
                              height: 78.0,
                              child: GeneratedGroup18Widget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 466.0,
                              right: null,
                              bottom: null,
                              width: 338.0,
                              height: 65.0,
                              child: GeneratedRectangle2Widget7(),
                            ),
                            Positioned(
                              left: 55.0,
                              top: 256.0,
                              right: null,
                              bottom: null,
                              width: 321.0,
                              height: 144.0,
                              child: GeneratedGroup19Widget(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 481.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 38.0,
                              child: GeneratedExpiryDateWidget(),
                            ),
                            Positioned(
                              left: 302.0,
                              top: 460.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 78.0,
                              child: GeneratedDownarrow1Widget1(),
                            ),
                            Positioned(
                              left: 49.0,
                              top: 853.0,
                              right: null,
                              bottom: null,
                              width: 333.0,
                              height: 61.0,
                              child: GeneratedMenubarWidget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
