import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedhomescreenwidget/generated/GeneratedLoadingWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedhomescreenwidget/generated/GeneratedLogoWidget6.dart';
import 'package:flutterapp/femmefindsapp/generatedhomescreenwidget/generated/GeneratedAonestopdestinationforwomenWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedhomescreenwidget/generated/GeneratedFEMMEFINDSWidget.dart';

/* Frame HomeScreen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedIntroPageWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: LayoutBuilder(
            builder: (BuildContext context, BoxConstraints constraints) {
          return SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: Container(
                height: 932.0,
                child: Stack(children: [
                  Container(
                      width: constraints.maxWidth,
                      child: Container(
                        width: 430.0,
                        height: 932.0,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(30.0),
                        ),
                        child: Stack(
                            fit: StackFit.expand,
                            alignment: Alignment.center,
                            overflow: Overflow.visible,
                            children: [
                              ClipRRect(
                                borderRadius: BorderRadius.circular(30.0),
                                child: Image.asset(
                                  "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                  color: null,
                                  fit: BoxFit.cover,
                                  width: 430.0,
                                  height: 932.0,
                                  colorBlendMode: BlendMode.dstATop,
                                ),
                              ),
                              Positioned(
                                left: 11.0,
                                top: 368.0,
                                right: null,
                                bottom: null,
                                width: 414.0,
                                height: 66.0,
                                child: GeneratedFEMMEFINDSWidget(),
                              ),
                              Positioned(
                                left: 34.0,
                                top: 481.0,
                                right: null,
                                bottom: null,
                                width: 364.0,
                                height: 79.0,
                                child:
                                    GeneratedAonestopdestinationforwomenWidget(),
                              ),
                              Positioned(
                                left: 125.0,
                                top: 761.0,
                                right: null,
                                bottom: null,
                                width: 186.0,
                                height: 64.0,
                                child: GeneratedLoadingWidget(),
                              ),
                              Positioned(
                                left: 178.0,
                                top: 245.0,
                                right: null,
                                bottom: null,
                                width: 75.0,
                                height: 71.0,
                                child: GeneratedLogoWidget6(),
                              )
                            ]),
                      ))
                ])),
          );
        }),
      ),
    ));
  }
}
