import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedcreateaccountwidget/generated/GeneratedConfirmPasswordWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedcreateaccountwidget/generated/GeneratedPasswordWidget3.dart';
import 'package:flutterapp/femmefindsapp/generatedcreateaccountwidget/generated/GeneratedGoogleFacebookSignupWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedcreateaccountwidget/generated/GeneratedLogoWidget3.dart';
import 'package:flutterapp/femmefindsapp/generatedcreateaccountwidget/generated/GeneratedCreateAnAccountWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedcreateaccountwidget/generated/GeneratedCreateButtonWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedcreateaccountwidget/generated/GeneratedUsernameWidget3.dart';

/* Frame CreateAccount
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCreateAccountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 178.0,
                              top: 175.0,
                              right: null,
                              bottom: null,
                              width: 75.0,
                              height: 71.0,
                              child: GeneratedLogoWidget3(),
                            ),
                            Positioned(
                              left: 62.0,
                              top: 272.0,
                              right: null,
                              bottom: null,
                              width: 308.0,
                              height: 42.0,
                              child: GeneratedCreateAnAccountWidget(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 338.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 90.0,
                              child: GeneratedUsernameWidget3(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 454.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 81.0,
                              child: GeneratedPasswordWidget3(),
                            ),
                            Positioned(
                              left: 73.0,
                              top: 561.0,
                              right: null,
                              bottom: null,
                              width: 285.0,
                              height: 81.0,
                              child: GeneratedConfirmPasswordWidget(),
                            ),
                            Positioned(
                              left: 105.0,
                              top: 775.0,
                              right: null,
                              bottom: null,
                              width: 220.0,
                              height: 110.0,
                              child: GeneratedGoogleFacebookSignupWidget(),
                            ),
                            Positioned(
                              left: 100.0,
                              top: 681.0,
                              right: null,
                              bottom: null,
                              width: 230.0,
                              height: 56.0,
                              child: GeneratedCreateButtonWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
