import 'package:flutter/material.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/Generated275Widget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedPaynowWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedPriceDetailsPrice1item275DeliveryChargesFreeWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedPaymentWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedAddressWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedOrderWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedStatusWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedRuppeWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedTransactionmodeWidget.dart';
import 'package:flutterapp/femmefindsapp/generatedpaymentdetailswidget/generated/GeneratedRupeeWidget.dart';

/* Frame PaymentDetails
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaymentDetailsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 932.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 430.0,
                      height: 932.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(30.0),
                              child: Image.asset(
                                "assets/images/c485120b8567be539adc701813b54a305fc873c9.png",
                                color: null,
                                fit: BoxFit.cover,
                                width: 430.0,
                                height: 932.0,
                                colorBlendMode: BlendMode.dstATop,
                              ),
                            ),
                            Positioned(
                              left: 56.0,
                              top: 159.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 46.0,
                              child: GeneratedStatusWidget(),
                            ),
                            Positioned(
                              left: 332.40185546875,
                              top: 224.0,
                              right: null,
                              bottom: null,
                              width: 83.0,
                              height: 29.0,
                              child: GeneratedPaymentWidget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 224.0,
                              right: null,
                              bottom: null,
                              width: 77.0,
                              height: 29.0,
                              child: GeneratedAddressWidget(),
                            ),
                            Positioned(
                              left: 197.0,
                              top: 224.0,
                              right: null,
                              bottom: null,
                              width: 58.0,
                              height: 29.0,
                              child: GeneratedOrderWidget(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 289.0,
                              right: null,
                              bottom: null,
                              width: 245.0,
                              height: 244.0,
                              child: GeneratedTransactionmodeWidget(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 594.0,
                              right: null,
                              bottom: null,
                              width: 382.0,
                              height: 122.0,
                              child:
                                  GeneratedPriceDetailsPrice1item275DeliveryChargesFreeWidget(),
                            ),
                            Positioned(
                              left: 332.0,
                              top: 639.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 30.0,
                              child: GeneratedRuppeWidget(),
                            ),
                            Positioned(
                              left: 332.0,
                              top: 737.0,
                              right: null,
                              bottom: null,
                              width: 26.0,
                              height: 30.0,
                              child: GeneratedRupeeWidget(),
                            ),
                            Positioned(
                              left: 141.0,
                              top: 845.0,
                              right: null,
                              bottom: null,
                              width: 146.0,
                              height: 39.0,
                              child: GeneratedPaynowWidget(),
                            ),
                            Positioned(
                              left: 37.0,
                              top: 743.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 29.0,
                              child: GeneratedTotalWidget(),
                            ),
                            Positioned(
                              left: 358.0,
                              top: 737.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 29.0,
                              child: Generated275Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
